- name: Execute initial server setup, Docker and GitHub CLI install
  hosts: all

- name: import server setup playbook
  import_playbook: ../playbooks/server-setup.yaml
    
- name: import docker playbook
  import_playbook: ../playbooks/docker.yaml

- name: import gh playbook
  import_playbook: ../playbooks/gh.yaml