- name: Update, upgrade, and clean up apt resources
  hosts: all
  become: true

  tasks:
    - name: Update apt
      apt:
        name: "*"
        state: latest

# Clean up apt resources
    - name: apt autoremove
      apt:
        autoremove: true
        autoclean: true
