- name: Install GitHub CLI
  hosts: all
  become: true

  tasks:
#    - name: Install gh
#      shell: type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
#        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
#        && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
#        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
#        && sudo apt update \
#        && sudo apt install gh -y
    
    - name: Add GitHub CLI GPG apt Key
      apt_key:
        url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
        state: present

    - name: Add GitHub CLI Repository
      apt_repository:
        repo: deb https://cli.github.com/packages stable main
        state: present

    - name: Update apt and install gh
      apt:
        name:
          - gh
        state: latest
        update_cache: true