- name: Install Nginx and CertBot
  hosts: webserver
  become: true

  tasks:

# Install Nginx and CertBot
    - name: Install Nginx
      apt:
        pkg:
          - nginx
          - certbot
        state: latest

# Create nginx user and group
    - name: Create nginx group
      group:
        name: nginx

    - name: Create nginx user
      user:
        name: nginx
        groups: nginx
        create_home: false
        shell: /bin/false

# Update firewall rules
    - name: UFW - Allow SSH connections
      community.general.ufw:
        rule: allow
        name: "Nginx Full"
